prooph_service_bus:
    command_buses:
        sylius_rbac_command_bus: ~

sylius_resource:
    resources:
        sylius_rbac.administration_role:
            classes:
                model: Sylius\RbacPlugin\Entity\AdministrationRole
                form: Sylius\RbacPlugin\Form\Type\AdministrationRoleType

sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: Sylius\RbacPlugin\Entity\AdminUser

sylius_grid:
    grids:
        sylius_rbac_administration_role:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\RbacPlugin\Entity\AdministrationRole
            fields:
                name:
                    type: string
                    label: sylius.ui.name
            actions:
                main:
                    create:
                        type: create
                        options:
                            link:
                                route: sylius_rbac_administration_role_new
                item:
                    update:
                        type: update
                        options:
                            link:
                                route: sylius_rbac_administration_role_edit
                                parameters:
                                    id: resource.id
        sylius_admin_admin_user:
            fields:
                administration_role:
                    type: twig
                    label: sylius_rbac.ui.administration_role
                    sortable: true
                    options:
                        template: '@SyliusRbacPlugin/AdministrationRole/Grid/Field/administrationRole.html.twig'
